### ISSUE TITLE
use native-or-bluebird module?

### ISSUE THREAD

**Issue by nightink** [WhoopInc/supertest-as-promised#12]
Hi @benesch 

I like you module, but my environment use iojs or node@~0.12.x.
I do not want to install bluebird module, so you can use [native-or-bluebird] module?
You agree, I can Pull request.

[native-or-bluebird]: https://github.com/normalize/native-or-bluebird

**Comment by nightink** [comment]
wow!!!!

supertest@1.1.0 `PR-268 - Bump superagent to 1.3.0`
https://github.com/visionmedia/supertest/blob/master/History.md#110--2015-08-26

superagent@1.3.0 `add basic promise support via a then function`
https://github.com/visionmedia/superagent/blob/master/History.md#130-2015-08-05

Sorry I use supertest module.

Thanks you module~

**Comment by nightink** [comment]
package.json `supertest: "*"`  It will lead to a test case error.

https://github.com/WhoopInc/supertest-as-promised/blob/master/package.json#L38
https://github.com/WhoopInc/supertest-as-promised/blob/master/test/index.js#L76

**Comment by benesch** [comment]
Good catch! That issue is now fixed on master.

Do note that the `.then()` method provided by SuperTest is not a full promise implementation: https://github.com/visionmedia/superagent/issues/722

**Comment by benesch** [comment]
Also, I prefer shipping Bluebird by default so that this library "just works" out of the box. The BYOP API allows you to swap in native ES6 promises if you prefer: do you have a compelling reason not to depend on Bluebird? It's only a few kilobytes of disk space.

**Comment by nightink** [comment]
visionmedia/superagent#709
> because I'm not going to be using it that way. catch is not useful in the co generator environment 

+1 co generator environment 
Please ignore me.
