### ISSUE TITLE
Can I use supertest's .end() function

### ISSUE THREAD

**Issue by nareshbhatia** [WhoopInc/supertest-as-promised#15]
For a certain test case, I would like to call supertest's `end()` function and take actions manually on success and failure. In other words, I don't want to use `expect()`. Is there an equivalent of the following supertest construct in supertest-as-promised?

    request.post(url)
        .send(myObject)
        .end(function(err, res) {
            ...
        });

Maybe something like:

    request.post(url)
        .send(myObject)
        .end()
        .then(function() {})
        .catch(function() {});

**Comment by nareshbhatia** [comment]
I tried this with supertest-as-promised (removed the endcall)

    request.post(url)
        .send(myObject)
        .then(function(res) {})
        .catch(function(err) {});

It seems that the then clause is called even when an error status code is returned.

**Comment by nareshbhatia** [comment]
Some more experimentation, threw in an `expect(201)`:

    request.post(url)
        .send(myObject)
        .expect(201)
        .then(function(res) {})
        .catch(function(err) {});

Now the catch is being called with an error object, but I loose the error code. All I have is an error message: *expected 201 "OK", got 403 "Forbidden"*.

**Comment by nareshbhatia** [comment]
Here's my workaround for now, please let me know if there is a better way:

    request.post(url)
        .send(myObject)
        .then(function(res) {
            return (res.ok) ? res.body : Promise.reject(new Error(res.statusCode));
        });

P.S. Is there a way to get a status message from the response object in addition to the status code. For example, "Forbidden" in addition to 403.

**Comment by nareshbhatia** [comment]
I am pretty happy with my workaround for now. Closing the issue. If anyone has better ideas, please feel free to comment.

**Comment by waisbrot** [comment]
Your work-around looks like Superagent to me. Are you sure you don't want that instead?

**Comment by nareshbhatia** [comment]
Good point! But then I loose all the promise-goodness I get with supertest-as-promised. Is there an easy way to add that in at the Superagent level?

**Comment by waisbrot** [comment]
I haven't tried it, but [Bluebird's promiseifyAll](http://bluebirdjs.com/docs/api/promise.promisifyall.html) seems worth a try.

**Comment by nareshbhatia** [comment]
I have tried it before I found supertest-as-promised. It seemed to work ok. However @benesch recommended against it (see https://github.com/WhoopInc/supertest-as-promised/issues/13):

> Bluebird's promisifyAll is incredibly annoying with SuperTest's API. You need to make sure to promisifyAll in exactly the right place.

**Comment by waisbrot** [comment]
He's talking about SuperTest, which is not the same thing as SuperAgent. And I believe the problems he saw with SuperTest are specific to the `expect` and other testing functions, which you're not using.

Mainly, I think if you're not using any testing features, you shouldn't use a testing library. :-)

**Comment by nareshbhatia** [comment]
Thanks, great points! I will try out SuperAgent *raw*. This also opens up the possibility of using https://github.com/request/request, another popular HTTP request library. Any opinions on that one? I think the API style is different (it not chaining like SuperAgent), but I have not seen any other comparisons.

**Comment by rfodge** [comment]
If you are using Jasmine and Supertest-as-promised, it looks like you will need to use the .end function (at least I needed to).  I could get it to work by doing:
   request
   .expect(200)
   .end( function(err) {
      expect(err).toBe(null);
      done();
   } );

**Comment by benesch** [comment]
Yes, you'll need a promise-compatible test runner like Mocha, or something like ThomasBurleson/jasmine-as-promised.

**Comment by rfodge** [comment]
I used: https://github.com/WhoopInc/supertest-as-promised

**Comment by benesch** [comment]
Right! But you'll need a test runner that supports promises. Out of the box, it appears Jasmine does not, so you'll need a promise shim like jasmine-as-promised if you want to be able to return promises directly. Otherwise, the approach you've taken is the way to go. Does that make sense?

**Comment by rfodge** [comment]
I was able to use Jasmine as is.  I didn't need to use jasmine-as-promised.  I was just suggesting he could use that, as that is what I'm currently using.  If you use Mocha, you do not need the .end function, but if you do Jasmine you do.

**Comment by benesch** [comment]
My point is that you shouldn't bother with supertest-as-promised if you're going to use the end callback—just use plain [supertest](github.com/visionmedia/supertest)! The whole point of this library is to eliminate the end function. If you use a test runner, like Jasmine, that doesn't support promises out of the box, you should use both jasmine-as-promised and supertest-as-promised, or neither.
