### ISSUE TITLE
Examine response

### ISSUE THREAD

**Issue by richardschneider** [WhoopInc/supertest-as-promised#16]
Is there anyway a can set a "hook" or use an `.on('response', ...)` to check the response before passing it to the actual test. 

I have a lot of tests against the API.  Want I want to do is verify that all responses match our spec without having to change each test.

**Comment by benesch** [comment]
Not that I know of! You may want to check upstream, though, with either visionmedia/supertest or visionmedia/superagent. (SuperTest as Promised strives not to change SuperTest beyond adding promise support.)
