### ISSUE TITLE
About toPromise()

### ISSUE THREAD

**Issue by tkrotoff** [WhoopInc/supertest-as-promised#17]
My bad: `toPromise()` returns a Bluebird promise. Anyway thx for fixing SuperTest.

~~`toPromise()` returns a ES6 Promise (https://github.com/WhoopInc/supertest-as-promised/blob/v2.0.2/index.js#L15)~~
then the example you give in the [README](https://github.com/WhoopInc/supertest-as-promised/blob/v2.0.2/README.md#promisey-goodness) is wrong:

```JavaScript
request(app)
  .get("/kittens")
  .expect(201)
  .toPromise()
  // I'm a real promise now!
  .delay(function(res) { /* ... */ })
  .then(function(res) { /* ... */ })
```

~~ES6 Promise does not have a `delay` function (https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise).~~ Bluebird [does](http://bluebirdjs.com/docs/api/delay.html) but it takes a number not a callback.

I question myself about the usefulness of `toPromise()`:
- ~~the name is confusing as `expect()` already returns a Promise (from Bluebird): it should be renamed to something like `toES6Promise()` or `toNativePromise()`~~
- ~~I don't think it is the role of the library to "convert" a Bluebird Promise to a ES6 Promise~~
- ~~Bluebird promises are already compatible with ES6 Promise: https://github.com/petkaantonov/bluebird/issues/655#issuecomment-111741561 => Bluebird acts as a superset~~

**Comment by benesch** [comment]
Good catch!
