### ISSUE TITLE
Access res.body when error occur

### ISSUE THREAD

**Issue by lius** [WhoopInc/supertest-as-promised#19]
I have a backend that returns error details on requisition response body. How can I access this information when catch is called, since it does not have access to res variable?

**Comment by waisbrot** [comment]
You may be able to `tap` the request to store the result outside of your promise chain. Or see if supertest has a cleaner solution. Finally, the correct solution for you may be either to use superagent directly or to consult your logs in the case of test failure.

**Comment by lius** [comment]
I agree and replaced it back again by supertest and it worked properly when using ```end(function(err, res))```. In my case the use application logs would make some automation much harder. Thanks for the response! The original idea was use promise interface with generators/async/await in mocha to improve productivity/readability on writing these tests.
