### ISSUE TITLE
Supertest needs to be required explicitly in npm 3.x

### ISSUE THREAD

**Issue by csaroff** [WhoopInc/supertest-as-promised#26]
As noted in the [README.md](https://github.com/WhoopInc/supertest-as-promised/blob/fe546de56127761451c6960c87392de89a6f2b4f/README.md#node) and PR #21, supertest needs to be explicitly required in the package.json of the project or the developer will receive a "supertest not found" error.  Is there any reason why this should be?  Is it possible to have supertest-as-promised simply require supertest in it's package.json?

**Comment by benesch** [comment]
The choice between a peer dependency and a standard dependency was clear in the days of NPM 2.x. Regardless of whether you specified a peer dependency, resulting in this dependency tree

```
foo
|- supertest@X
|- supertest-as-promised
```

or a standard dependency, resulting in this tree

```
foo
|- supertest@X
|- supertest-as-promised
   |- supertest@Y
```

NPM would install both for you. But with the standard dependency, you have two versions of supertest floating around: the stock version X and the promisified version Y. With the peer dependency, you have stock version X and promisified version X. The peer dependency is the clear winner.

Now that NPM doesn't automatically install peer dependencies, foo is forced to manually list it as a dependency, as you've discovered. There's a cost to this annoyance, for sure, but I still think peer dependencies are the way to go. If we switch SuperTest to a standard dependency, we'd need to release a new version of SuperTest-as-Promised for every version of SuperTest. (Or we'd pin to the latest version, `*`, but that would prevent upstream packages from pinning to a more specific version of SuperTest without the hopelessly useless piece-of-crap that is [npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap).)

Let me know if you have a counterargument!

**Comment by csaroff** [comment]
Thanks for the update to the streamlined installation instructions.  

+1 to not using shrinkwrap.

I'm not sure if this is possible, but the desired behavior in my view would be 
```
npm install --save-dev supertest-as-promised
```
If you want a specific version of supertest to "back it" you would also 
```
npm install --save-dev supertest
```
If you were using npm 3 and you had not installed supertest it would grab the latest version.  Is this exactly the behaviour in npm 2 and if so, do you know why the changed it?

Ultimately, it isn't a big hastle, but it feels odd to me to include a module in my package.json which I never explicitly require.  I often go through and remove any unused dependencies in my package.json by grepping my code for "require('modulename')" and see if it's used anywhere.

**Comment by benesch** [comment]
In NPM 2,  `npm install --save-dev supertest-as-promised` was equivalent to `npm install --save-dev supertest supertest-as-promised` in NPM 3. That is, even in NPM 2, supertest would be listed in package.json as a dependency.

 If you're interested in the politics behind this change: https://github.com/npm/npm/issues/5080

Unfortunately, I don't see a way to switch SuperTest to a regular dependency instead of a peer dependency unless `npm shrinkwrap` becomes viable. I don't currently have the bandwidth to keep up with SuperTest development and release corresponding SuperTest as Promised versions.

**Comment by csaroff** [comment]
@benesch 

Thank you very much for spending time clarifying this issue.  The current solution seems to be the "correct way" of packaging things according to npm.  It

**Comment by benesch** [comment]
Of course! Thanks for your interest. :)
