### ISSUE TITLE
How can I get the server address?

### ISSUE THREAD

**Issue by alexbooker** [WhoopInc/supertest-as-promised#28]
Hi, how can I get the server address?

```
import app from './app'
const client = supertest(app)

client.get('/api/customers').then(response => {

})

// how do I find out what port supertest-as-promised is using?
```

Thanks.

**Comment by waisbrot** [comment]
It's got super-agent underneath, so check out http://visionmedia.github.io/superagent/#request-basics

**Comment by alexbooker** [comment]
Thanks.

I'm sorry, but I don't see anything relating to the `listener` address or port in the documentation.

**Comment by waisbrot** [comment]
So, if you're using relative paths then you're probably not actually making an HTTP connection and hostname and port aren't meaningful. If you're using a full URL then you encode the host and port there: `https://example.com:8084/my/cool/path?key=val&good=true`

**Comment by alexbooker** [comment]
I appreciate that this isn't strictly a **`supertest-as-promised`** question, so I'm especially grateful for your help.

I use relative paths:

```js
const {statusCode, text} = await supertest(app)
  .get('/api/screencasts')

```

Thing is, If I look at **`req.headers.host`** from within a route handler called by **`supertest`**, I can see the port number:

![](http://i.imgur.com/XvIDxRd.png)

So I'm a bit confused. I was hoping to access the server's port as described [here](http://stackoverflow.com/a/4842885/5147646).

Thanks.

**Comment by waisbrot** [comment]
Without seeing the code that's generating that "trace" line, I'd guess that you're printing the host:port that you're connecting _from_. Is that what you want?

Better question: what do you actually want to do? Why is it important to know the server address or port number? There are a few different things that could be considered to be the host address. Like, you might have multiple CNAMES or you might have a load balancer in front and you could be interested in the LB's address or the address of the server behind the LB...

**Comment by benesch** [comment]
You can tap into SuperTest's private API:

```
var request = require('supertest'),
    express = require('express');

var app = express();

// Save intermediate state.
var test = request(app).get('/user');

// Extract address object. `test.app` is an instance of `http.Server`.
test.app.address(); // { address: '::', family: 'IPv6', port: 62821 }

// Perform assertions.
test
  .expect(404)
  .end(function(err, res) {
    if (err) throw err;
  });
```

Best of luck!
