### ISSUE TITLE
supertest isn't listed as a dependency

### ISSUE THREAD

**Issue by thebigredgeek** [WhoopInc/supertest-as-promised#29]
This package won't work unless I explicitly install supertest along side.  This seems like an error.  Would a PR to fix this be accepted?

**Comment by thebigredgeek** [comment]
Oh, I see it is being listed as a peerDependency.  AFAIK, peerDependencies are being depreciated :/

**Comment by benesch** [comment]
Not deprecated, just changed to a new, annoying behavior by NPM 3. See #26 for more.
