### ISSUE TITLE
When an expect fails (resulting in an error), the response is lost.

### ISSUE THREAD

**Issue by mkasberg** [WhoopInc/supertest-as-promised#30]
Suppose we expect a 200, but actually get a 422 (or some other error code), with info about the error in the response.

    return request(app)
      .get("/user")
      .expect(200)
      .then(function (res) {
        // Do stuff ...
      })
      .catch(function (err) {
        // PROBLEM. Don't have response from server.
      });

If we go into the `catch`, there's no way to print the server's response.

**Comment by hyzhak** [comment]
definitely should be in a lib
