### ISSUE TITLE
Agent not persisting cookies

### ISSUE THREAD

**Issue by wlingke** [WhoopInc/supertest-as-promised#35]
My code looks like this:

```
      const api = request.agent(server.listen());
      await api.post(sessionAPI)
      .send({ email, password })
      .expect(200); //the "set-cookie" header exists here.

      //the "Cookie" header does not exist here
      await api.get(sessionAPI)
      .expect(200);
```

Am I missing something to make this work?

**Comment by waisbrot** [comment]
I believe your question is about [superagent](https://github.com/visionmedia/superagent). supertest-as-promised is a promisifying wrapper around supertest which is a layer atop superagent.

**Comment by wlingke** [comment]
okay thanks
