### ISSUE TITLE
How to use plugins for supertest

### ISSUE THREAD

**Issue by rpieciorak** [WhoopInc/supertest-as-promised#37]
Is there any way currently to use plugins for superagent?

Maybe wrapper should also expose `superagent.use` method?

**Comment by benesch** [comment]
If you call `.use` after you call `.get`, `.post`, etc., it should work, I think. See also #33. Please report back!

**Comment by rpieciorak** [comment]
Yes it's working with `superagent-default`. Thanks for help.

My goal was to use `superagent-use` with `superagent-prefix` to prefix request urls because i'm lazy and do not like repeat itself.

First try ends with failure - request urls wasn't prefixed at all.
After some debugging I discovered that its because `superagent-prefix` expects relative url.

So I'm posting my solution for some another lazy developer ;)

``` javascript
var app = require('app');
var asPromised = require('supertest-as-promised')(global.Promise);
var request = require('superagent-defaults')(asPromised(app));

var prefixPlugin = function(prefix) {
  return function(request) {
    var url = require('url');
    var reqUrl = url.parse(request.url);
    if (reqUrl.pathname[0] === '/') {
      reqUrl.pathname = prefix + reqUrl.pathname;
    }
    request.url = url.format(reqUrl);
    return request;
  }
}

request.use(prefix('/api/v1'))

describe('When sending request', function() {
   it('should prefix url with /api/v1', function() {
     return request.get('/users').expect(200);
   }
}
```

**Comment by waisbrot** [comment]
Thanks!
