### ISSUE TITLE
Add breaking changes note and tags for the 4.0 and 4.0.1 release?

### ISSUE THREAD

**Issue by karlbecker** [WhoopInc/supertest-as-promised#39]
I typically click on the releases tab in GitHub to check out what some of the versions are of an npm module.  I see the most recent release in that section is 3.2, but the [package.json history](https://github.com/WhoopInc/supertest-as-promised/commits/master/package.json) indicates 4.0.0 and 4.0.1 have been released.

Could the breaking changes be added to the bottom of the readme, and a tag or two made for the new release?

Thanks!

**Comment by benesch** [comment]
Thanks for catching this, @karlbecker! README has been updated, tags have been pushed, and I've set Travis up to auto-deploy tagged commits, which should force me to push tags up in the future.

**Comment by karlbecker** [comment]
Rock on - thanks so much, @benesch !
