### ISSUE TITLE
TypeError: Cannot set property 'state' of undefined

### ISSUE THREAD

**Issue by miparnisari** [WhoopInc/supertest-as-promised#43]
I'm using `supertest-as-promised` 4.0.2.

The test goes like this:

  ```javascript
  var request = require('supertest-as-promised');
  var should  = require('should');
  var app = require('../server.js');

  it('checks something', function(done) {
     request(app)
      .put('/users?access_token=' + accessToken)
      .send({})
      .expect(200)
      .then(function() {
        return models.User.findById(userId);
      })
      .then(function (user) {
        should.exist(user);
        return request(app).get('/users?access_token=' + accessToken)
      })
      .then(function () {
        done();  // <---- error thrown here
      })
      .catch(function (err) {
        done(err);
      })
    });
   ```

And *sometimes* I get this error:

     TypeError: Cannot set property 'state' of undefined
      at test\users.js:264:9
      at tryCatch1 (node_modules\supertest-as-promised\node_modules\bluebird\js\main\util.js:63:19)
      at Promise$_callHandler [as _callHandler] (node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:695:13)
      at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:711:18)
      at Promise$_settlePromiseAt [as _settlePromiseAt] (node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:868:14)
      at Promise$_settlePromises [as _settlePromises] (node_modules\supertest-as-promised\node_modules\bluebird\js\main\promise.js:1006:14)
      at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (node_modules\supertest-as-promised\node_modules\bluebird\js\main\async.js:74:12)
      at Async$consumeFunctionBuffer (node_modules\supertest-as-promised\node_modules\bluebird\js\main\async.js:37:14)
```

**Comment by benesch** [comment]
Hi! Thanks for reporting your issue. This doesn't quite smell like a SuperTest as Promised issue to me, given that the offending code you've included doesn't use SuperTest as Promised at all. I'll note to start that your code seems to have an incorrect semicolon (this wouldn't even run, would it?)

```js
it('checks something', function(done) {
   models.User.findOne({ where: {actorId : userId}); // <-- here
    .then(function (u) {
      should.exist(u);
      return models.User.destroy({where: {actorId : userId}});
    })
    .then(function () {
      done();  // <---- error thrown here
    })
    .catch(function (err) {
      done(err);
    })
  });
```

and that if you're using a promise-compatible test runner you can just return promises directly:

```js
it('checks something', function() {
   return models.User.findOne({ where: {actorId : userId})
    .then(function (u) {
      should.exist(u);
      return models.User.destroy({where: {actorId : userId}});
    })
  });
```

To fully debug, though, I'd need to see what the other test cases in the file were that actually used SuperTest as Promised. Any chance you can send along the minimum entire file that causes the issue?

**Comment by miparnisari** [comment]
@benesch Wow, that was a fast response. I've edited the original post with code that more resembles the actual test. I don't know if its relevant or not but I'm calling `request` more than once in my test.

**Comment by benesch** [comment]
Posting from mobile, so please excuse the lack of a full code sample. The second time you call request, try calling `.toPromise` on the the request before returning it. So `return request(app).get(...).toPromise()`. Shouldn't be necessary though. Hmm!

**Comment by miparnisari** [comment]
That gives me `TypeError: request(...).get(...).toPromise is not a function`.

What worries me is that if I run this test alone it always passes, it fails only when I run it with all my other tests.

**Comment by benesch** [comment]
Sorry for the delay! I'm inclined to think this is a race condition elsewhere in your code, but I'm afraid I can't give you more insight without seeing the rest of your tests.

In any case, I'm going to close this issue because SuperTest as Promised is now deprecated as per #44. I've added [instructions for upgrading to SuperTest 2.0](https://github.com/WhoopInc/supertest-as-promised#supertest-as-promised) to the README.

If you upgrade to SuperTest 2.0 and the bug disappears, that means you probably did find a bug in SuperTest as Promised. Do let me know if that's the case! I'd like to fix the bug for users who don't want to upgrade to SuperTest 2.0.

**Comment by miparnisari** [comment]
Hey, the problem was on my side! As it turns out, the version in `npm-shrinkwrap.json` was 0.15.0 and the version on `package.json` was 2.0.0, but it was using the older one!

**Comment by benesch** [comment]
Thanks for letting me know, and glad to hear it! NPM shrinkwrap is an eternal nightmare.
