### ISSUE TITLE
Promise functionality already supported in supertest

### ISSUE THREAD

**Issue by jasisk** [WhoopInc/supertest-as-promised#44]
Hi there.

A colleague included `supertest-as-promised` in one of our repos which caused me to look you up. 😀

If I'm not mistaken, the functionality you're after is already available with supertest. Since it inherits from superagent (which has first-class promise support), it Just Works™. I did notice the app-chaining capability in your example—a similar functionality is already exposed via `Supertest.agent`.

Here's a pretty simple test case (_ugh boilerplate_ but the meat is in here somewhere):
``` js
const Supertest = require('supertest');
const Router = require('router');
const Http = require('http');

const router = Router();
const listener = (...args) => router(...args, console.error);
const server = Http.createServer(listener);
const request = Supertest.agent(server);

const response = status => (req, res) => {
  console.log('request received, waiting 1000ms ...');
  setTimeout(() => {
    console.log(`sending ${status} response ...`);
    res.writeHead(status);
    res.end();
  }, 1000);
};

const test = endpoint => request.get(endpoint)
  .expect(200)
  .then(() => console.log('Test passed.'))
  .catch(err => console.error('Test failed:', err.message));

router.get('/success', response(200));
router.get('/failure', response(500));

test('/success').then(() => test('/failure'));
```

... and the output:
```
request received, waiting 1000ms ...
sending 200 response ...
Test passed.
request received, waiting 1000ms ...
sending 500 response ...
Test failed: expected 200 "OK", got 500 "Internal Server Error"
```

Just a friendly PSA from one Bostonian to another. Do with that info (that you may already have!) as you will. :grinning:

**EDIT**: and if I'm totally off-base, 1) wouldn't be the first time and 2) don't mind me.

**Comment by mikew** [comment]
I just noticed this by accident when switching a project to `supertest-as-promised`. After removing `done` callbacks and returning the `request` object, everything worked even though I forgot to switch `require('supertest')` to `require('supertest-as-promised')`

**Comment by benesch** [comment]
Yup, as of July SuperTest started shipping a version of SuperAgent with proper promise support! And as of September `.catch()` is built in, so you almost certainly don't need this project for new libraries.

Some users are relying on the returned promise object being a Bluebird promise instance, though (instead of an ES6 `Promise` instance), so I'll continue to maintain the library in the near-term. I'll add a deprecation notice to the README and install notes soon.

**Comment by benesch** [comment]
Thanks again for bringing this to my attention, @jasisk.
